In [5]:
import tensorflow as tf
import numpy as np

In [6]:
X = np.array([1.0, 2.0, 3.0, 4.0, 5.0, 6.0 ])
Y = np.array([110.0, 210.0, 310.0, 410.0, 510.0, 610.0])

In [7]:
Y

array([110., 210., 310., 410., 510., 610.])

In [8]:
model = tf.keras.Sequential([tf.keras.layers.Dense(units = 1, input_shape = [1])])
model.compile(optimizer = 'sgd', loss = 'mean_squared_error')
model.fit(X, Y, epochs = 100, verbose = 1)

Epoch 1/100
1/1 [==============================] - 0s 3ms/step - loss: 154121.6562
Epoch 2/100
1/1 [==============================] - 0s 3ms/step - loss: 71347.6250
Epoch 3/100
1/1 [==============================] - 0s 3ms/step - loss: 33037.2227
Epoch 4/100
1/1 [==============================] - 0s 2ms/step - loss: 15305.8994
Epoch 5/100
1/1 [==============================] - 0s 2ms/step - loss: 7099.1987
Epoch 6/100
1/1 [==============================] - 0s 3ms/step - loss: 3300.7812
Epoch 7/100
1/1 [==============================] - 0s 3ms/step - loss: 1542.6533
Epoch 8/100
1/1 [==============================] - 0s 998us/step - loss: 728.8290
Epoch 9/100
1/1 [==============================] - 0s 2ms/step - loss: 352.0588
Epoch 10/100
1/1 [==============================] - 0s 1ms/step - loss: 177.5712
Epoch 11/100
1/1 [==============================] - 0s 2ms/step - loss: 96.7060
Epoch 12/100
1/1 [==============================] - 0s 1ms/step - loss: 59.1738
Epoch 13/100
1/1 [=======

In [9]:
a8 = np.array([7.0])
yhat = model.predict(a8)

In [10]:
yhat

array([[704.56635]], dtype=float32)

In [11]:
X = np.array([[2, 6], 
              [3, 7], 
              [4, 9], 
              [2, 10], 
              [6, 7], 
              [3, 8], 
              [1, 7]])
Y = np.array([60, 69, 75, 59, 76, 77, 68])

In [12]:
model = tf.keras.Sequential([tf.keras.layers.Dense(units = 1, input_shape = [2])])
model.compile(optimizer = 'sgd', loss = 'mean_squared_error')
model.fit(X, Y, epochs = 200, verbose = 1)

Epoch 1/200
1/1 [==============================] - 0s 2ms/step - loss: 5670.6636
Epoch 2/200
1/1 [==============================] - 0s 2ms/step - loss: 1125.1222
Epoch 3/200
1/1 [==============================] - 0s 2ms/step - loss: 306.4971
Epoch 4/200
1/1 [==============================] - 0s 2ms/step - loss: 158.2950
Epoch 5/200
1/1 [==============================] - 0s 2ms/step - loss: 130.7551
Epoch 6/200
1/1 [==============================] - 0s 2ms/step - loss: 124.9882
Epoch 7/200
1/1 [==============================] - 0s 2ms/step - loss: 123.2017
Epoch 8/200
1/1 [==============================] - 0s 2ms/step - loss: 122.1899
Epoch 9/200
1/1 [==============================] - 0s 2ms/step - loss: 121.3709
Epoch 10/200
1/1 [==============================] - 0s 2ms/step - loss: 120.6356
Epoch 11/200
1/1 [==============================] - 0s 2ms/step - loss: 119.9603
Epoch 12/200
1/1 [==============================] - 0s 2ms/step - loss: 119.3365
Epoch 13/200
1/1 [=================

1/1 [==============================] - 0s 2ms/step - loss: 106.5242
Epoch 102/200
1/1 [==============================] - 0s 2ms/step - loss: 106.4480
Epoch 103/200
1/1 [==============================] - 0s 2ms/step - loss: 106.3717
Epoch 104/200
1/1 [==============================] - 0s 2ms/step - loss: 106.2957
Epoch 105/200
1/1 [==============================] - 0s 2ms/step - loss: 106.2197
Epoch 106/200
1/1 [==============================] - 0s 1ms/step - loss: 106.1437
Epoch 107/200
1/1 [==============================] - 0s 2ms/step - loss: 106.0679
Epoch 108/200
1/1 [==============================] - 0s 2ms/step - loss: 105.9921
Epoch 109/200
1/1 [==============================] - 0s 1ms/step - loss: 105.9165
Epoch 110/200
1/1 [==============================] - 0s 999us/step - loss: 105.8409
Epoch 111/200
1/1 [==============================] - 0s 1ms/step - loss: 105.7654
Epoch 112/200
1/1 [==============================] - 0s 999us/step - loss: 105.6899
Epoch 113/200
1/1 [=======

1/1 [==============================] - 0s 2ms/step - loss: 99.3295


### Test learning

In [13]:
istanza = np.array([[5, 9]])


In [14]:
yhat = model.predict(istanza)

In [15]:
yhat 


array([[85.16033]], dtype=float32)

In [16]:
istanza2 = np.array([[1, 6]])
yhat = model.predict(istanza2)
yhat

array([[47.893307]], dtype=float32)

In [17]:
istanza3 = np.array([[3, 7]])
yhat =  model.predict(istanza3)
yhat

array([[63.470345]], dtype=float32)